<template>
  <div>
    <div v-if="gettingAllItems">LOADING...</div>
    <div v-else>
      <div>
        <div v-for="({ item }, i) in allItems" :key="i" style="margin: 6px 0px">
          <span style="margin-right: 4px">{{ item.name }}</span>
          <button @click="$router.push(`/test/${item.id}`)">Edit</button>
        </div>
      </div>
      <button @click="add()">{{ adding ? "Adding..." : "Add" }}</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { storeToRefs } from "pinia";
import { useTestStore } from "~/stores/testStore";

const store = useTestStore();
const { getAllItems, createItem } = store;
const { allItems, gettingAllItems } = storeToRefs(store);
gettingAllItems.value = true;

const adding = ref(false);
const add = async () => {
  adding.value = true;
  // this is a hack - the id would be generated by the server
  const nextId = allItems.value.length + 1;
  await createItem({
    id: nextId,
    name: `New Item ${nextId}`,
  });
  adding.value = false;
};

onMounted(async () => {
  // do this on every page load, but it will cache in the store
  await getAllItems();
});
</script>
